spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/java-orderprocessing
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cache:
    type: redis

app:
  rabbitmq:
    queue: order.queue
    exchange: order.exchange
    routing-key: order.routing.key


